### ISSUE TITLE
Installing mods on the Steam Deck

### ISSUE THREAD

**Issue by tjohnman** [Myonmu/WoH-Community-Modding-Guide#1]
I just now realized I have never worked with GitHub wikies, so I'm sorry if opening an issue is not the correct way to call your attention on this.

I have noticed there are no Steam Deck instructions on the "How To Install Mods" page and maybe you would like to add some.

On the Steam Deck, the path where the "custom" and "character" directories should go is: `/home/deck/.local/share/Steam/steamapps/compatdata/913740/pfx/drive_c/users/steamuser/AppData/Local/wohgame`
If you can't find it for some reason, I found it by running `find /home/deck -iname save.ito` on the Konsole terminal. Since it's the same directory where the `save.ito` file is.

**Comment by Myonmu** [comment]
Noted, I will transfer this message to Haspen to keep both side updated.
