### ISSUE TITLE
The code strings for additional status sprites on Custom Characters?

### ISSUE THREAD

**Issue by soulozempic** [Myonmu/WoH-Community-Modding-Guide#2]
Hi there,

Been testing a custom character of mine the past two days and been noting masks and items that I want to show up on the character
portrait--the most reoccurring being Funny Mask, Kendo mask and Happi coat.

I started with the Funny Mask, made the sprite and then figured I would wing it on the string of code. 
'funny_mask="mycharacterfolder\Funnymask.png'

I am very new to this, I managed to get the rest of the character's statuses running so I don't know if its an issue on my end or if the code for status images beyond what is on the guide just isn't available.

Thanks so much for the helpful guide!

**Comment by Myonmu** [comment]
> Hi there,
> 
> Been testing a custom character of mine the past two days and been noting masks and items that I want to show up on the character
> portrait--the most reoccurring being Funny Mask, Kendo mask and Happi coat.
> 
> 
> I started with the Funny Mask, made the sprite and then figured I would wing it on the string of code. 
> 'funny_mask="mycharacterfolder\Funnymask.png'
> 
> I am very new to this, I managed to get the rest of the character's statuses running so I don't know if its an issue on my end or if the code for status images beyond what is on the guide just isn't available.
> 
> Thanks so much for the helpful guide! 

Hi,

Currently only a subset of the status sprites  are exposed to modders, what you mentioned are unfortunately not supported.

**Comment by soulozempic** [comment]
> > Hi there,
> > Been testing a custom character of mine the past two days and been noting masks and items that I want to show up on the character
> > portrait--the most reoccurring being Funny Mask, Kendo mask and Happi coat.
> > I started with the Funny Mask, made the sprite and then figured I would wing it on the string of code.
> > 'funny_mask="mycharacterfolder\Funnymask.png'
> > I am very new to this, I managed to get the rest of the character's statuses running so I don't know if its an issue on my end or if the code for status images beyond what is on the guide just isn't available.
> > Thanks so much for the helpful guide!
> 
> Hi,
> 
> Currently only a subset of the status sprites are exposed to modders, what you mentioned are unfortunately not supported.

I see,
Thank you for clarifying! And thanks again for the helpful guides!
